title: Researcher
url: "https://pkmklong.github.io"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/pkmklong"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "index"
# - name: "Resume"
#   link: "resume.pdf"
# - name: "Tutorials"
#  link: "tutorials"
 - name: "Contact"
   link: "contact"
